### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by fecony** [boywithkeyboard-archive/cheetah1#128]
I know it's possible to write code like following to version api:

```ts
api
  .use('/v1', v1Routes)
  .use('/v2', v2Routes);
```

But If I want to implement something like Header versioning or other type like nestjs has https://docs.nestjs.com/techniques/versioning I will have to write some magic extension code (I believe)

Would be cool a) to have global config to specify default version, specify version for one route? configure how versioning is specified/handled

**Comment by boywithkeyboard** [comment]
Noted for ~~v1.2~~ v1.4!

**Comment by boywithkeyboard** [comment]
Closed with #180
