### ISSUE TITLE
Setup script - folder name param

### ISSUE THREAD

**Issue by fecony** [boywithkeyboard-archive/cheetah1#130]
Now when running `deno run -Ar https://deno.land/x/cheetah/setup.ts` you cannot specify name, neither write it before/after being asked about runtime. And we end up with `cheetahland-template-deno-basic-6ae3a45` folder that has to be renamed manually
A small DX touch to let developer specify folder name where to place new project

**Comment by boywithkeyboard** [comment]
This fits perfectly into the v1.2 release as I plan to move the templates to the main repository anyway.
