### ISSUE TITLE
Helpers to register custom routes from extension

### ISSUE THREAD

**Issue by fecony** [boywithkeyboard-archive/cheetah1#134]
Would be helpful to make a way to add new routes from custom extension to extend code
Maybe developers could use it to simply add extension like `.use(healthcheck())` that would register it's own route `/healthcheck` and add some logic before that

For now it's kinda possible to do by adding it to `app.routes` Set, but it can be improved to make it as easy as `app.routes.add('GET', '/healtcheck, (c) => '💚')` or with `.get` / `.post` methods

**Comment by boywithkeyboard** [comment]
It would work like that:
```ts
app.routes.add(['GET', '/', new RegExp('path to regexp'), [() => 'Hello World']])
```
