### ISSUE TITLE
`req.text()` sets additional `Content-Type` header

### ISSUE THREAD

**Issue by kibibites** [boywithkeyboard-archive/cheetah1#31]
I have this code:
```ts
app.get("/", (ctx) => {
  ctx.res.header("Content-Type", "text/html");
  ctx.res.text(Deno.readTextFileSync("./index.html").replace("$TURNSTILE_SITE_KEY", Deno.env.get("TURNSTILE_SITE_KEY") || ""));
});
```

It should send a `Content-Type: text/html` header, however, it adds another `text/plain; charset=utf-8` header. Is this expected behavior?

Screenshot:
![image](https://github.com/azurystudio/cheetah/assets/47074495/20ac4f8c-ec2b-4683-a6f6-c434783412c3)

**Comment by boywithkeyboard** [comment]
@not-ivy This is definitely **not** intentional. I'll publish a bug fix later today.

I'm sorry for the inconvenience.

*A small side note:*

```ts
app.get("/", (ctx) => {
  ctx.res.header("Content-Type", "text/html");
  return Deno.readTextFileSync("./index.html").replace("$TURNSTILE_SITE_KEY", Deno.env.get("TURNSTILE_SITE_KEY") || "");
})
```

I'd suggest to *return* the data and not use the `c.res.text` method as this is just unnecessary boilerplate.
