### ISSUE TITLE
`ctx.req` isn't a standard `Request` object

### ISSUE THREAD

**Issue by kibibites** [boywithkeyboard-archive/cheetah1#39]
I am trying to upgrade a connection to a websocket connection, and according to the Deno documentation, `Deno.upgradeWebsocket()` is what I should use. However, `ctx.req` is not a standard `Request` object, therefore it cannot be used with that method. Is there a way that I can get a standard `Request` object?

Demo code:
```
import cheetah from "https://deno.land/x/cheetah@v0.7.2/mod.ts";
import { serve } from "https://deno.land/std@0.187.0/http/server.ts";

const app = new cheetah();
app.get("/upgrade", (ctx) => {
  Deno.upgradeWebSocket(ctx.req)
})
```

**Comment by kibibites** [comment]
sorry, I guess I didn't read the docs carefully enough :p
It is documented here: https://github.com/azurystudio/cheetah/blob/dev/guide/request.md#get-raw-request

**Comment by boywithkeyboard** [comment]
@not-ivy yeah, the `c.req` object is a custom variant with various cheetah-specific features. Thank you tho for your help in making cheetah better for everyone!

**Comment by boywithkeyboard** [comment]
Also as a side note, there's already a [milestone](https://github.com/azurystudio/cheetah/milestone/1) for the major v1 release which will come with a much better documentation.
